import './globals.css'
import 'aos/dist/aos.css';
import { Inter } from 'next/font/google'
import visbyFont from '@/constants/visbyFont';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${visbyFont.variable} ${inter.className}`}>{children}</body>
    </html>
  )
}
